### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chr15m** [mnmmt/hardhat#1]
* [ ] Get new interface working.
 * [ ] Get Pi A+ version working.
 * [ ] Test with 220 mods.
 * [ ] Ability to add mods to SD card.
 * [ ] Iterate on current case: close holes.
 * [ ] Test out printed latches instead of screws.
 * [ ] Packaging.
